# Generated by Django 5.2.7 on 2025-10-25 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('fecha', models.DateTimeField()),
                ('fecha_palabra', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('lugar', models.CharField(max_length=200)),
                ('precio', models.DecimalField(decimal_places=0, max_digits=10)),
                ('imagen', models.CharField(max_length=200)),
            ],
        ),
    ]
