# Generated by Django 5.2.7 on 2025-10-26 20:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='capacidad',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='evento',
            name='inscritos',
            field=models.ManyToManyField(blank=True, related_name='eventos_inscritos', to=settings.AUTH_USER_MODEL),
        ),
    ]
